# The word that needs to be said to receive the reward
word: "welcome"
# The time in seconds within which users must say the word
timer: 20
# Command to be executed for the reward
commands:
    - eco give [playerName] 100
messages:
    prefix: "&7[&aWelcomeReward&7]"
    reward-message: "&bYou recived &d$100 &bfor welcoming a new player!"
    config-reload: "&aConfig succesfully reloaded!"
    no-permission: "&4You do not have permission!"